[package]
name = "shapemap_oxgraph"
version.workspace = true
authors.workspace = true
documentation = "https://docs.rs/shapemap_oxgraph"
edition.workspace = true


[dependencies]
shapemap = { workspace = true }
oxrdf = "0.1.7"
thiserror = "2.0"
