[package]
name = "srdf_graph"
version = "0.0.2"
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
iri_s = { path = "../iri_s", version = "0.0.2" }
srdf = { path = "../srdf", version = "0.0.2" }
prefix_map = { path = "../prefix_map", version = "0.0.2" }
rio_api = "0.8.2"
rio_turtle = "0.8.2"
oxrdf = "0.1.6"
oxiri = "0.2"
thiserror = "1.0"
async-trait = "0.1.68"
tokio = { version = "1", features = ["full"] }
colored = "2"
log = "0.4"
env_logger = "0.10"


