[package]
name = "shapemap"
version = "0.0.4"
authors.workspace = true
description.workspace = true
documentation = "https://docs.rs/shapemap"
edition.workspace = true
license.workspace = true

[dependencies]
iri_s = { path = "../iri_s", version = "0.0.4" }
prefixmap = { path = "../prefixmap", version = "0.0.4" }
thiserror = "1.0"
nom = "7"
nom_locate = "4"
log = "0.4"


[dev-dependencies]
env_logger = "0.10"
tracing-subscriber = {version = "0.3", default-features = false, features = ["env-filter", "fmt"]}
test-log = "0.2.12"
