[package]
name = "srdf_sparql"
version = "0.0.4"
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true


[dependencies]
oxrdf = "0.1.6"
oxiri = "0.2"
async-trait = "0.1.68"
iri_s = { path = "../iri_s", version = "0.0.4" }
srdf = { path = "../srdf", version = "0.0.4" }
# oxhttp = { version = "0.1.6", features = ["rustls"] }
sparesults = "0.1.8"
reqwest = { version = "0.11.18", features = ["blocking", "json"] }
url = "2.2.2"
tokio = { version = "1", features = ["full"] }
thiserror = "1.0"




