[package]
name = "dctap"
version = "0.1.6"
authors.workspace = true
description.workspace = true
documentation = "https://docs.rs/dctap"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
csv = "1.3.0"
calamine = "0.25"
indexmap = { version = "2"}
itertools = "0.13"
iri_s = { path = "../iri_s", version = "0.1.5" }
prefixmap = { path = "../prefixmap", version = "0.1.0" }
serde = "1.0"
serde_json = "1.0"
serde_yml = "0.0.11"
serde_derive = "1.0"
serde_with = "3.8.1"
thiserror = "1"
tracing = "0.1"

[dev-dependencies]
tracing-test = "0.1"
