[package]
name = "shex_ast"
version = "0.0.4"
authors.workspace = true
description.workspace = true
documentation = "https://docs.rs/shex_ast"
edition.workspace = true
license.workspace = true

[dependencies]
srdf = { path = "../srdf", version = "0.0.4" }
iri_s = { path = "../iri_s", version = "0.0.4" }
rbe = { path = "../rbe", version = "0.0.4" }
prefixmap = { path = "../prefixmap", version = "0.0.4" }
serde = "1"
serde_derive = "1"
void = "1"
thiserror = "1.0"
log = "0.4"
lazy_static = "1"
rust_decimal = "1.32"
rust_decimal_macros = "1.32"
regex = "1.10"
serde_json = "1"

[dev-dependencies]
env_logger = "0.10"
test-log = "0.2.12"
