[package]
name = "shex_validation"
version = "0.1.6"
authors.workspace = true
description.workspace = true
documentation = "https://docs.rs/shex_validation"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
iri_s = { workspace = true }
rbe = { workspace = true }
srdf = { workspace = true }
shex_ast = { workspace = true }
shapemap = { workspace = true }
prefixmap = { workspace = true }
async-recursion = "1.0.4"
thiserror = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = { workspace = true }
tokio = { version = "^1.35", features = ["full"] }
tracing = { workspace = true }
indexmap = { version = "2" }
colored = "2"
either = "1"
serde_yml = "0.0.11"

[dev-dependencies]
oxrdf = { workspace = true }
