[package]
name = "shex_validation"
version = "0.1.145"
authors.workspace = true
description.workspace = true
documentation = "https://docs.rs/shex_validation"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

#[features]
#default = []

[dependencies]
either.workspace = true # "1"
indexmap.workspace = true # { version = "2" }
iri_s.workspace = true
itertools.workspace = true
prefixmap.workspace = true
rbe.workspace = true
serde.workspace = true
serde_json.workspace = true
shex_ast.workspace = true
rdf.workspace = true
termtree.workspace = true
thiserror.workspace = true 
toml.workspace = true
tracing.workspace = true
url.workspace = true
