[package]
name = "rbe_testsuite"
version = "0.0.3"
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rbe = { path = "../rbe", version = "0.0.3" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.9"
anyhow = "1.0.27"
log = "0.4"

[dev-dependencies]
indoc = "2"
env_logger = "0.10"
test-log = "0.2.12"

