[package]
name = "shex_testsuite"
version = "0.1.147"
authors.workspace = true
description.workspace = true
documentation = "https://docs.rs/shex_testsuite"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0"
clap.workspace = true
iri_s.workspace = true
prefixmap.workspace = true
serde.workspace = true
serde_json = { workspace = true }
shex_ast.workspace = true
# shex_compact.workspace = true
shex_validation.workspace = true
# shapemap.workspace = true
rdf.workspace = true
thiserror.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
