[package]
name = "shapes_converter"
version = "0.1.17"
authors.workspace = true
description.workspace = true
documentation = "https://docs.rs/shapes_converter"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
rdf-star = [
    "spargebra/rdf-star",
    "srdf/rdf-star",
]


[dependencies]
iri_s = { workspace = true }
dctap = { workspace = true }
rbe = { workspace = true }
srdf = { workspace = true }
shacl_ast = { workspace = true }
shex_ast = { workspace = true }
shex_compact = { workspace = true }
shapemap = { workspace = true }
prefixmap = { workspace = true }
colored = "2"
either = "1"
indexmap = { version = "2" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { workspace = true }
serde_yml = "0.0.11"
serde_derive = "1.0"

spargebra = "0.3.0-alpha.5"
thiserror = "1.0"
tracing = { workspace = true }
minijinja = { version = "2.0.3", features = ["loader"] }
tempfile = "3.10.1"

[dev-dependencies]
oxrdf = { workspace = true }
