[package]
name = "shapes_converter"
version = "0.1.79"
authors.workspace = true
description.workspace = true
documentation = "https://docs.rs/shapes_converter"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

#[features]
#rdf-star = [
#    "spargebra/rdf-star",
#    "srdf/rdf-star",
#]

[dependencies]
iri_s.workspace = true
dctap.workspace = true
srdf.workspace = true
shacl_ast.workspace = true
shex_ast.workspace = true
shex_compact.workspace = true
shex_validation.workspace = true
shacl_validation.workspace = true
prefixmap.workspace = true
serde.workspace = true
toml = "0.8"
chrono = "0.4.38"

spargebra.workspace = true
thiserror = "2.0"
tracing = { workspace = true }
minijinja = { version = "2.0.3", features = ["loader"] }
tempfile.workspace = true
