[package]
name = "shex_cli"
version = "0.0.5"
authors.workspace = true
description.workspace = true
documentation = "https://www.weso.es/shex-rs/"
edition.workspace = true
license.workspace = true

[dependencies]
shex_ast = { path = "../shex_ast", version = "0.0.5" }
shex_validation = { path = "../shex_validation", version = "0.0.5" }
srdf = { path = "../srdf", version = "0.0.5" }
prefixmap = { path = "../prefixmap", version = "0.0.5" }
srdf_graph = { path = "../srdf_graph", version = "0.0.5" }
srdf_sparql = { path = "../srdf_sparql", version = "0.0.5" }
iri_s = { path = "../iri_s", version = "0.0.5" }
shapemap = { path = "../shapemap", version = "0.0.5" }
shex_compact = { path = "../shex_compact", version = "0.0.5" }

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.9.21"
anyhow = "1.0"
thiserror = "1.0"
void = "1"
clap = { version = "4.2.1", features = ["derive"] }
rio_api = "0.8.2"
rio_turtle = "0.8.2"
oxrdf = "0.1.6"
oxiri = "0.2"
log = "0.4"
env_logger = "0.10"
regex = "1"
