[package]
name = "shex_cli"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[dependencies]
shex_ast = { path = "../shex_ast" }
srdf = { path = "../srdf" }
srdf_graph = { path = "../srdf_graph" }
iri_s = { path = "../iri_s" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.9.21"
anyhow = "1.0"
thiserror = "1.0"
void = "1"
clap = { version = "4.2.1", features = ["derive"] }
rio_api = "0.8.2"
rio_turtle = "0.8.2"
oxrdf = "0.1.6"
oxiri = "0.2"
log = "0.4"
env_logger = "0.10"
regex = "1"